flask:
  build: Dockerfiles/python-flask-pymongo
#  volumes:
#    - code:/code
  links:
    - mongodb
  ports:
    - "5000:5000"
mongodb:
  build: Dockerfiles/mongo
#   volumes:
#     - data:/data
  ports:
    - "27017:27017"
